import { ModelConfig } from "./models";

export interface CostResult {
    inputCost: number;
    outputCost: number;
    totalCost: number;
}

// ── Turn-by-turn data shape returned by calculateLoopCost ──────────────────
export interface LoopTurnData {
    turn: number;
    inputTokens: number;        // context window size at this turn
    turnCost: number;           // cost for this specific turn
    cumulativeCost: number;     // running total cost up to and including this turn
}

export interface LoopTotals {
    finalInputTokens: number;   // projected context size after the last turn grows
    totalInputCost: number;
    totalOutputCost: number;
    totalCost: number;
}

export interface LoopResult {
    turnData: LoopTurnData[];
    totals: LoopTotals;
}

/**
 * Calculates the compounding token cost over multiple iterations.
 *
 * Each turn the context window grows:
 *   nextInput = currentInput + avgOutputTokens + avgNewInputTokens
 *
 * @param baseInputTokens  - Tokens from the initial system + user prompt.
 * @param avgOutputTokens  - Estimated tokens generated by the model per turn.
 * @param avgNewInputTokens - Estimated new tokens injected per turn (tool results, etc.).
 * @param iterations       - Total number of loop iterations.
 * @param model            - Selected ModelConfig (provides pricing).
 */
export function calculateLoopCost(
    baseInputTokens: number,
    avgOutputTokens: number,
    avgNewInputTokens: number,
    iterations: number,
    model: ModelConfig
): LoopResult {
    const inputPricePerToken = model.inputPricePer1M / 1_000_000;
    const outputPricePerToken = model.outputPricePer1M / 1_000_000;

    let currentInputTokens = baseInputTokens;
    let cumulativeInputCost = 0;
    let cumulativeOutputCost = 0;

    const turnData: LoopTurnData[] = [];

    for (let turn = 1; turn <= iterations; turn++) {
        // 1. Cost for the current turn
        const turnInputCost = currentInputTokens * inputPricePerToken;
        const turnOutputCost = avgOutputTokens * outputPricePerToken;
        const turnTotalCost = turnInputCost + turnOutputCost;

        // 2. Accumulate
        cumulativeInputCost += turnInputCost;
        cumulativeOutputCost += turnOutputCost;

        // 3. Record for chart
        turnData.push({
            turn,
            inputTokens: currentInputTokens,
            turnCost: turnTotalCost,
            cumulativeCost: cumulativeInputCost + cumulativeOutputCost,
        });

        // 4. Grow context for the NEXT turn
        currentInputTokens += avgOutputTokens + avgNewInputTokens;
    }

    return {
        turnData,
        totals: {
            finalInputTokens: currentInputTokens,
            totalInputCost: cumulativeInputCost,
            totalOutputCost: cumulativeOutputCost,
            totalCost: cumulativeInputCost + cumulativeOutputCost,
        },
    };
}

// ── Legacy shim kept for any other callers ──────────────────────────────────
/** @deprecated Use calculateLoopCost instead. */
export interface LoopTurn {
    turn: number;
    cumulativeInputTokens: number;
    outputTokens: number;
    turnCost: number;
    runningTotal: number;
}

/**
 * Calculate cost for a single call given input tokens, output tokens, and model pricing.
 */
export function calculateCost(
    inputTokens: number,
    outputTokens: number,
    model: ModelConfig
): CostResult {
    const inputCost = (inputTokens / 1_000_000) * model.inputPricePer1M;
    const outputCost = (outputTokens / 1_000_000) * model.outputPricePer1M;
    return {
        inputCost,
        outputCost,
        totalCost: inputCost + outputCost,
    };
}

/**
 * Classify cost into a tier for the gauge visual.
 */
export function getCostTier(totalCost: number): "cheap" | "moderate" | "expensive" {
    if (totalCost < 0.01) return "cheap";
    if (totalCost < 0.10) return "moderate";
    return "expensive";
}

// ── Caching Cost Logic ──────────────────────────────────────────────────────

export interface CacheCostResult {
    isSupported: boolean;
    standardInputCost: number;
    cachedInputCost: number; // Cost after first run (Read static from cache + standard dynamic)
    outputCost: number;
    totalStandardCost: number;
    totalCachedCost: number;
}

/**
 * Calculates the cost of a prompt with and without context caching.
 * @param staticTokens - The large context that is cached (e.g. codebase, documents)
 * @param dynamicTokens - The per-request varied context (e.g. user prompt)
 * @param outputTokens - The expected generated tokens
 * @param model - Selected model config
 */
export function calculateCacheCost(
    staticTokens: number,
    dynamicTokens: number,
    outputTokens: number,
    model: ModelConfig
): CacheCostResult {
    // 1. Stand normal calculation
    const totalInputTokens = staticTokens + dynamicTokens;
    const stdInputCost = (totalInputTokens / 1_000_000) * model.inputPricePer1M;
    const outCost = (outputTokens / 1_000_000) * model.outputPricePer1M;

    // Check if caching is supported for this model and meets minimum token threshold
    const isBelowThreshold = model.minCacheTokens ? staticTokens < model.minCacheTokens : false;
    const isSupported = model.cacheReadPricePer1M !== undefined && !isBelowThreshold;

    // 2. Cached calculation (after first run)
    // The static context is read from the cache, the dynamic is completely standard input
    let cachedInputCost = stdInputCost; // default to standard if unsupported or below threshold
    if (isSupported && model.cacheReadPricePer1M !== undefined) {
        const staticReadCost = (staticTokens / 1_000_000) * model.cacheReadPricePer1M;
        const dynamicCost = (dynamicTokens / 1_000_000) * model.inputPricePer1M;
        cachedInputCost = staticReadCost + dynamicCost;
    }

    return {
        isSupported,
        standardInputCost: stdInputCost,
        cachedInputCost,
        outputCost: outCost,
        totalStandardCost: stdInputCost + outCost,
        totalCachedCost: cachedInputCost + outCost,
    };
}
