export interface ModelConfig {
  id: string;
  name: string;
  provider: string;
  providerSlug?: string;
  inputPricePer1M: number;   // USD per 1M input tokens
  outputPricePer1M: number;  // USD per 1M output tokens
  cacheWritePricePer1M?: number; // USD per 1M tokens written to cache
  cacheReadPricePer1M?: number;  // USD per 1M tokens read from cache
  minCacheTokens?: number;       // Minimum tokens required to trigger caching
  cacheTtlLimit?: number;        // Typical cache TTL in minutes
  maxContext: number;        // max context window in tokens
  tier?: 'flagship' | 'balanced' | 'fast' | 'budget' | 'reasoning';
  supportsVision?: boolean;
  cachingAvailable?: boolean;
  batchDiscount?: number;    // 0.5 for 50% discount
  tpmLimit?: number;         // Typical Tokens Per Minute limit
  rpmLimit?: number;         // Typical Requests Per Minute limit
  deprecated?: boolean;
  freeTier?: boolean;
  notes?: string;
  pricingUrl?: string;
  benchmarks?: {
    mmlu?: number;
    humanEval?: number;
    sweBench?: number;
  };
  latencyMs?: number; // average latency in ms
  visionPricing?: {
    strategy: "openai-tiles" | "anthropic-scale" | "gemini-flat";
    baseTokens?: number; // For OpenAI base
    tileTokens?: number; // For OpenAI tiles
    flatTokens?: number; // For Gemini flat
  };
}

// Pricing last updated: April 2026
// Sources: Official provider pricing pages
export const models: ModelConfig[] = [
  // ── OpenAI ──────────────────────────────────────────────────────────────
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    providerSlug: 'openai',
    inputPricePer1M: 2.50,
    outputPricePer1M: 10.00,
    maxContext: 128000,
    tier: 'balanced',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    pricingUrl: 'https://openai.com/api/pricing/',
    latencyMs: 850,
    visionPricing: { strategy: 'openai-tiles', baseTokens: 85, tileTokens: 170 }
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o mini',
    provider: 'OpenAI',
    providerSlug: 'openai',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.60,
    maxContext: 128000,
    tier: 'fast',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    pricingUrl: 'https://openai.com/api/pricing/',
    latencyMs: 450,
    visionPricing: { strategy: 'openai-tiles', baseTokens: 85, tileTokens: 170 }
  },
  {
    id: 'gpt-4.1',
    name: 'GPT-4.1',
    provider: 'OpenAI',
    providerSlug: 'openai',
    inputPricePer1M: 2.00,
    outputPricePer1M: 8.00,
    maxContext: 1000000,
    tier: 'balanced',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    pricingUrl: 'https://openai.com/api/pricing/',
    latencyMs: 780,
    visionPricing: { strategy: 'openai-tiles', baseTokens: 85, tileTokens: 170 }
  },
  {
    id: 'gpt-4.1-mini',
    name: 'GPT-4.1 mini',
    provider: 'OpenAI',
    providerSlug: 'openai',
    inputPricePer1M: 0.40,
    outputPricePer1M: 1.60,
    maxContext: 1000000,
    tier: 'fast',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    pricingUrl: 'https://openai.com/api/pricing/',
    latencyMs: 380,
    visionPricing: { strategy: 'openai-tiles', baseTokens: 85, tileTokens: 170 }
  },
  {
    id: 'gpt-5',
    name: 'GPT-5',
    provider: 'OpenAI',
    providerSlug: 'openai',
    inputPricePer1M: 1.25,
    outputPricePer1M: 10.00,
    maxContext: 400000,
    tier: 'flagship',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    pricingUrl: 'https://openai.com/api/pricing/',
    latencyMs: 1200,
    visionPricing: { strategy: 'openai-tiles', baseTokens: 85, tileTokens: 170 }
  },
  {
    id: 'gpt-5-mini',
    name: 'GPT-5 mini',
    provider: 'OpenAI',
    providerSlug: 'openai',
    inputPricePer1M: 0.40,
    outputPricePer1M: 1.60,
    maxContext: 200000,
    tier: 'balanced',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    pricingUrl: 'https://openai.com/api/pricing/',
    latencyMs: 420,
    visionPricing: { strategy: 'openai-tiles', baseTokens: 85, tileTokens: 170 }
  },
  {
    id: 'o1',
    name: 'o1',
    provider: 'OpenAI',
    providerSlug: 'openai',
    inputPricePer1M: 15.00,
    outputPricePer1M: 60.00,
    maxContext: 200000,
    tier: 'reasoning',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    notes: 'Reasoning model. Internal thinking tokens billed as output — actual cost higher than visible output suggests.',
    pricingUrl: 'https://openai.com/api/pricing/',
    latencyMs: 5500,
    visionPricing: { strategy: 'openai-tiles', baseTokens: 85, tileTokens: 170 }
  },
  {
    id: 'o3',
    name: 'o3',
    provider: 'OpenAI',
    providerSlug: 'openai',
    inputPricePer1M: 10.00,
    outputPricePer1M: 40.00,
    maxContext: 200000,
    tier: 'reasoning',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    notes: 'Reasoning model. Internal thinking tokens billed as output.',
    pricingUrl: 'https://openai.com/api/pricing/',
    latencyMs: 3500,
    visionPricing: { strategy: 'openai-tiles', baseTokens: 85, tileTokens: 170 }
  },
  {
    id: 'o4-mini',
    name: 'o4-mini',
    provider: 'OpenAI',
    providerSlug: 'openai',
    inputPricePer1M: 1.10,
    outputPricePer1M: 4.40,
    maxContext: 200000,
    tier: 'reasoning',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    notes: 'Budget reasoning model. Great for math and coding at lower cost than o1/o3.',
    pricingUrl: 'https://openai.com/api/pricing/',
    latencyMs: 1800,
    visionPricing: { strategy: 'openai-tiles', baseTokens: 85, tileTokens: 170 }
  },

  // ── Anthropic ────────────────────────────────────────────────────────────
  {
    id: 'claude-opus-4-6',
    name: 'Claude Opus 4.6',
    provider: 'Anthropic',
    providerSlug: 'anthropic',
    inputPricePer1M: 5.00,
    outputPricePer1M: 25.00,
    maxContext: 1000000,
    tier: 'flagship',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    latencyMs: 1400,
    pricingUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
    visionPricing: { strategy: 'anthropic-scale' }
  },
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    provider: 'Anthropic',
    providerSlug: 'anthropic',
    inputPricePer1M: 3.00,
    outputPricePer1M: 15.00,
    maxContext: 1000000,
    tier: 'balanced',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    latencyMs: 850,
    notes: 'Long context surcharge (>200K tokens): $6.00 input / $22.50 output',
    pricingUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
    visionPricing: { strategy: 'anthropic-scale' }
  },
  {
    id: 'claude-haiku-4-5-20251001',
    name: 'Claude Haiku 4.5',
    provider: 'Anthropic',
    providerSlug: 'anthropic',
    inputPricePer1M: 1.00,
    outputPricePer1M: 5.00,
    maxContext: 200000,
    tier: 'fast',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    latencyMs: 400,
    pricingUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
    visionPricing: { strategy: 'anthropic-scale' }
  },
  {
    id: 'claude-opus-4-1',
    name: 'Claude Opus 4.1 (legacy)',
    provider: 'Anthropic',
    providerSlug: 'anthropic',
    inputPricePer1M: 15.00,
    outputPricePer1M: 75.00,
    maxContext: 200000,
    tier: 'flagship',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    latencyMs: 2200,
    pricingUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
    visionPricing: { strategy: 'anthropic-scale' }
  },
  {
    id: 'claude-sonnet-4-5',
    name: 'Claude Sonnet 4.5',
    provider: 'Anthropic',
    providerSlug: 'anthropic',
    inputPricePer1M: 3.00,
    outputPricePer1M: 15.00,
    maxContext: 1000000,
    tier: 'balanced',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    latencyMs: 950,
    pricingUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
    visionPricing: { strategy: 'anthropic-scale' }
  },
  {
    id: 'claude-haiku-3-5',
    name: 'Claude Haiku 3.5',
    provider: 'Anthropic',
    providerSlug: 'anthropic',
    inputPricePer1M: 0.80,
    outputPricePer1M: 4.00,
    maxContext: 200000,
    tier: 'fast',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    latencyMs: 500,
    pricingUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
    visionPricing: { strategy: 'anthropic-scale' }
  },
  {
    id: 'claude-haiku-3',
    name: 'Claude Haiku 3',
    provider: 'Anthropic',
    providerSlug: 'anthropic',
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.25,
    maxContext: 200000,
    tier: 'budget',
    supportsVision: false,
    cachingAvailable: true,
    deprecated: true,
    notes: '⚠️ Deprecated April 19 2026. Migrate to Haiku 4.5.',
    pricingUrl: 'https://platform.claude.com/docs/en/about-claude/pricing'
  },

  // ── Google ───────────────────────────────────────────────────────────────
  {
    id: 'gemini-3.1-pro',
    name: 'Gemini 3.1 Pro',
    provider: 'Google',
    providerSlug: 'google',
    inputPricePer1M: 2.00,
    outputPricePer1M: 12.00,
    maxContext: 2000000,
    tier: 'flagship',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    latencyMs: 1100,
    notes: 'Long context surcharge (>200K tokens): 2x input price',
    pricingUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
    visionPricing: { strategy: 'gemini-flat', flatTokens: 258 }
  },
  {
    id: 'gemini-3-flash',
    name: 'Gemini 3 Flash',
    provider: 'Google',
    providerSlug: 'google',
    inputPricePer1M: 0.50,
    outputPricePer1M: 3.00,
    maxContext: 1000000,
    tier: 'balanced',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    latencyMs: 350,
    pricingUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
    visionPricing: { strategy: 'gemini-flat', flatTokens: 258 }
  },
  {
    id: 'gemini-2.5-pro-preview-05-06',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    providerSlug: 'google',
    inputPricePer1M: 1.25,
    outputPricePer1M: 10.00,
    maxContext: 1000000,
    tier: 'balanced',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    latencyMs: 950,
    notes: 'Long context (>200K tokens): $2.50/$15 per 1M.',
    pricingUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
    visionPricing: { strategy: 'gemini-flat', flatTokens: 258 }
  },
  {
    id: 'gemini-2.5-flash-preview-04-17',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    providerSlug: 'google',
    inputPricePer1M: 0.30,
    outputPricePer1M: 2.50,
    maxContext: 1000000,
    tier: 'fast',
    supportsVision: true,
    cachingAvailable: true,
    freeTier: true,
    batchDiscount: 0.5,
    latencyMs: 400,
    pricingUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
    visionPricing: { strategy: 'gemini-flat', flatTokens: 258 }
  },
  {
    id: 'gemini-2.5-flash-lite-preview-06-17',
    name: 'Gemini 2.5 Flash-Lite',
    provider: 'Google',
    providerSlug: 'google',
    inputPricePer1M: 0.10,
    outputPricePer1M: 0.40,
    maxContext: 1000000,
    tier: 'budget',
    supportsVision: true,
    cachingAvailable: true,
    freeTier: true,
    batchDiscount: 0.5,
    latencyMs: 250,
    pricingUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
    visionPricing: { strategy: 'gemini-flat', flatTokens: 258 }
  },
  {
    id: 'gemini-2.0-flash-001',
    name: 'Gemini 2.0 Flash',
    provider: 'Google',
    providerSlug: 'google',
    inputPricePer1M: 0.10,
    outputPricePer1M: 0.40,
    maxContext: 1000000,
    tier: 'budget',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    latencyMs: 300,
    pricingUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
    visionPricing: { strategy: 'gemini-flat', flatTokens: 258 }
  },
  {
    id: 'gemini-2.0-flash-lite',
    name: 'Gemini 2.0 Flash-Lite',
    provider: 'Google',
    providerSlug: 'google',
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.30,
    maxContext: 1000000,
    tier: 'budget',
    supportsVision: true,
    cachingAvailable: true,
    deprecated: true,
    notes: '⚠️ Deprecated — shuts down June 1, 2026.',
    pricingUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
    visionPricing: { strategy: 'gemini-flat', flatTokens: 258 }
  },
  {
    id: 'gemini-1.5-pro-002',
    name: 'Gemini 1.5 Pro',
    provider: 'Google',
    providerSlug: 'google',
    inputPricePer1M: 1.25,
    outputPricePer1M: 5.00,
    maxContext: 2000000,
    tier: 'balanced',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    pricingUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
    visionPricing: { strategy: 'gemini-flat', flatTokens: 258 }
  },
  {
    id: 'gemini-1.5-flash-002',
    name: 'Gemini 1.5 Flash',
    provider: 'Google',
    providerSlug: 'google',
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.30,
    maxContext: 1000000,
    tier: 'fast',
    supportsVision: true,
    cachingAvailable: true,
    batchDiscount: 0.5,
    pricingUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
    visionPricing: { strategy: 'gemini-flat', flatTokens: 258 }
  },

  // ── xAI ──────────────────────────────────────────────────────────────────
  {
    id: 'grok-4',
    name: 'Grok 4',
    provider: 'xAI',
    providerSlug: 'xai',
    inputPricePer1M: 3.00,
    outputPricePer1M: 15.00,
    maxContext: 2000000,
    tier: 'flagship',
    supportsVision: true,
    cachingAvailable: false,
    latencyMs: 1200,
    pricingUrl: 'https://x.ai/api',
    visionPricing: { strategy: 'openai-tiles', baseTokens: 85, tileTokens: 170 }
  },
  {
    id: 'grok-4.1-fast',
    name: 'Grok 4.1 Fast',
    provider: 'xAI',
    providerSlug: 'xai',
    inputPricePer1M: 0.20,
    outputPricePer1M: 0.50,
    maxContext: 2000000,
    tier: 'fast',
    supportsVision: false,
    cachingAvailable: false,
    notes: 'Best value for massive context window (2M tokens) at budget price.',
    pricingUrl: 'https://x.ai/api'
  },
  {
    id: 'grok-3',
    name: 'Grok 3',
    provider: 'xAI',
    providerSlug: 'xai',
    inputPricePer1M: 3.00,
    outputPricePer1M: 15.00,
    maxContext: 131000,
    tier: 'balanced',
    supportsVision: false,
    cachingAvailable: false,
    pricingUrl: 'https://x.ai/api'
  },
  {
    id: 'grok-3-mini',
    name: 'Grok 3 Mini',
    provider: 'xAI',
    providerSlug: 'xai',
    inputPricePer1M: 0.30,
    outputPricePer1M: 0.50,
    maxContext: 131000,
    tier: 'budget',
    supportsVision: false,
    cachingAvailable: false,
    pricingUrl: 'https://x.ai/api'
  },

  // ── DeepSeek ─────────────────────────────────────────────────────────────
  {
    id: 'deepseek-v4',
    name: 'DeepSeek V4',
    provider: 'DeepSeek',
    providerSlug: 'deepseek',
    inputPricePer1M: 0.30,
    outputPricePer1M: 0.50,
    maxContext: 1000000,
    tier: 'flagship',
    supportsVision: false,
    cachingAvailable: true,
    latencyMs: 1600,
    notes: 'Cache hit: $0.03/M input (90% off). Infrastructure in China — latency varies outside Asia.',
    pricingUrl: 'https://platform.deepseek.com/api-docs/pricing'
  },
  {
    id: 'deepseek-chat',
    name: 'DeepSeek V3.2',
    provider: 'DeepSeek',
    providerSlug: 'deepseek',
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    maxContext: 128000,
    tier: 'balanced',
    supportsVision: false,
    cachingAvailable: true,
    latencyMs: 700,
    notes: 'One of the cheapest high-quality models available. Cache hit: $0.028/M input.',
    pricingUrl: 'https://platform.deepseek.com/api-docs/pricing'
  },
  {
    id: 'deepseek-reasoner',
    name: 'DeepSeek R1',
    provider: 'DeepSeek',
    providerSlug: 'deepseek',
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    maxContext: 128000,
    tier: 'reasoning',
    supportsVision: false,
    cachingAvailable: true,
    latencyMs: 4500,
    notes: 'Reasoning model. ~96% cheaper than OpenAI o1 for comparable tasks.',
    pricingUrl: 'https://platform.deepseek.com/api-docs/pricing'
  },

  // ── Mistral AI ──────────────────────────────────────────────────────────
  {
    id: 'mistral-large-latest',
    name: 'Mistral Large 3',
    provider: 'Mistral',
    providerSlug: 'mistral',
    inputPricePer1M: 2.00,
    outputPricePer1M: 6.00,
    maxContext: 131000,
    tier: 'flagship',
    supportsVision: true,
    cachingAvailable: false,
    freeTier: true,
    notes: 'Cheapest output price in its capability tier. EU data residency available.',
    pricingUrl: 'https://mistral.ai/pricing',
    visionPricing: { strategy: 'openai-tiles', baseTokens: 85, tileTokens: 170 }
  },
  {
    id: 'mistral-medium-latest',
    name: 'Mistral Medium 3',
    provider: 'Mistral',
    providerSlug: 'mistral',
    inputPricePer1M: 1.00,
    outputPricePer1M: 3.00,
    maxContext: 131000,
    tier: 'balanced',
    supportsVision: false,
    cachingAvailable: false,
    freeTier: true,
    pricingUrl: 'https://mistral.ai/pricing'
  },
  {
    id: 'mistral-small-latest',
    name: 'Mistral Small 3.1',
    provider: 'Mistral',
    providerSlug: 'mistral',
    inputPricePer1M: 0.20,
    outputPricePer1M: 0.60,
    maxContext: 131000,
    tier: 'fast',
    supportsVision: false,
    cachingAvailable: false,
    freeTier: true,
    pricingUrl: 'https://mistral.ai/pricing'
  },
  {
    id: 'codestral-latest',
    name: 'Codestral',
    provider: 'Mistral',
    providerSlug: 'mistral',
    inputPricePer1M: 0.20,
    outputPricePer1M: 0.60,
    maxContext: 256000,
    tier: 'balanced',
    supportsVision: false,
    cachingAvailable: false,
    freeTier: true,
    notes: 'Specialized for code generation and completion.',
    pricingUrl: 'https://mistral.ai/pricing'
  },
  {
    id: 'open-mistral-nemo',
    name: 'Mistral Nemo',
    provider: 'Mistral',
    providerSlug: 'mistral',
    inputPricePer1M: 0.03,
    outputPricePer1M: 0.03,
    maxContext: 128000,
    tier: 'budget',
    supportsVision: false,
    cachingAvailable: false,
    freeTier: true,
    notes: 'One of the cheapest capable models available anywhere.',
    pricingUrl: 'https://mistral.ai/pricing'
  },
  {
    id: 'ministral-8b-latest',
    name: 'Ministral 8B',
    provider: 'Mistral',
    providerSlug: 'mistral',
    inputPricePer1M: 0.10,
    outputPricePer1M: 0.10,
    maxContext: 128000,
    tier: 'budget',
    supportsVision: false,
    cachingAvailable: false,
    freeTier: true,
    pricingUrl: 'https://mistral.ai/pricing'
  },

  // ── Meta Llama (via Together AI) ──────────────────────────────────────────
  {
    id: 'meta-llama/Llama-4-Maverick-17B-128E-Instruct',
    name: 'Llama 4 Maverick',
    provider: 'Meta (Together AI)',
    providerSlug: 'meta',
    inputPricePer1M: 0.27,
    outputPricePer1M: 0.85,
    maxContext: 1000000,
    tier: 'flagship',
    supportsVision: true,
    cachingAvailable: false,
    notes: 'Open-weight model. Self-hosting is free. Prices shown for hosted inference via Together AI.',
    pricingUrl: 'https://www.together.ai/pricing',
    visionPricing: { strategy: 'openai-tiles', baseTokens: 85, tileTokens: 170 }
  },
  {
    id: 'meta-llama/Llama-4-Scout-17B-16E-Instruct',
    name: 'Llama 4 Scout',
    provider: 'Meta (Together AI)',
    providerSlug: 'meta',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.60,
    maxContext: 512000,
    tier: 'balanced',
    supportsVision: false,
    cachingAvailable: false,
    notes: 'Open-weight. Self-hosting is free.',
    pricingUrl: 'https://www.together.ai/pricing'
  },
  {
    id: 'meta-llama/Llama-3.3-70B-Instruct',
    name: 'Llama 3.3 70B',
    provider: 'Meta (Together AI)',
    providerSlug: 'meta',
    inputPricePer1M: 0.23,
    outputPricePer1M: 0.40,
    maxContext: 131000,
    tier: 'balanced',
    supportsVision: false,
    cachingAvailable: false,
    notes: 'Open-weight. Strong open-source baseline.',
    pricingUrl: 'https://www.together.ai/pricing'
  },
  {
    id: 'meta-llama/Meta-Llama-3.1-405B-Instruct',
    name: 'Llama 3.1 405B',
    provider: 'Meta (Together AI)',
    providerSlug: 'meta',
    inputPricePer1M: 0.80,
    outputPricePer1M: 0.80,
    maxContext: 128000,
    tier: 'flagship',
    supportsVision: false,
    cachingAvailable: false,
    notes: 'Largest open-weight model. Self-hostable.',
    pricingUrl: 'https://www.together.ai/pricing'
  },

  // ── Cohere ───────────────────────────────────────────────────────────
  {
    id: 'command-r-plus',
    name: 'Command R+',
    provider: 'Cohere',
    providerSlug: 'cohere',
    inputPricePer1M: 2.50,
    outputPricePer1M: 10.00,
    maxContext: 128000,
    tier: 'flagship',
    supportsVision: false,
    cachingAvailable: false,
    notes: 'Strong for RAG and enterprise search workflows.',
    pricingUrl: 'https://cohere.com/pricing'
  },
  {
    id: 'command-r',
    name: 'Command R',
    provider: 'Cohere',
    providerSlug: 'cohere',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.60,
    maxContext: 128000,
    tier: 'balanced',
    supportsVision: false,
    cachingAvailable: false,
    pricingUrl: 'https://cohere.com/pricing'
  },

  // ── Alibaba Qwen ────────────────────────────────────────────────────────
  {
    id: 'qwen3-235b-a22b',
    name: 'Qwen 3 235B A22B',
    provider: 'Alibaba',
    providerSlug: 'alibaba',
    inputPricePer1M: 0.22,
    outputPricePer1M: 0.60,
    maxContext: 131000,
    tier: 'flagship',
    supportsVision: false,
    cachingAvailable: false,
    pricingUrl: 'https://help.aliyun.com/en/model-studio/developer-reference/pricing'
  },
  {
    id: 'qwq-32b',
    name: 'QwQ 32B',
    provider: 'Alibaba',
    providerSlug: 'alibaba',
    inputPricePer1M: 0.30,
    outputPricePer1M: 0.80,
    maxContext: 131000,
    tier: 'reasoning',
    supportsVision: false,
    cachingAvailable: false,
    notes: 'Reasoning model from Qwen family.',
    pricingUrl: 'https://help.aliyun.com/en/model-studio/developer-reference/pricing'
  },

  // ── Amazon ───────────────────────────────────────────────────────────
  {
    id: 'amazon.nova-pro-v1:0',
    name: 'Amazon Nova Pro',
    provider: 'Amazon',
    providerSlug: 'amazon',
    inputPricePer1M: 0.80,
    outputPricePer1M: 3.20,
    maxContext: 300000,
    tier: 'balanced',
    supportsVision: true,
    cachingAvailable: false,
    notes: 'Available via AWS Bedrock.',
    pricingUrl: 'https://aws.amazon.com/bedrock/pricing/',
    visionPricing: { strategy: 'openai-tiles', baseTokens: 85, tileTokens: 170 }
  },
  {
    id: 'amazon.nova-lite-v1:0',
    name: 'Amazon Nova Lite',
    provider: 'Amazon',
    providerSlug: 'amazon',
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.24,
    maxContext: 300000,
    tier: 'fast',
    supportsVision: true,
    cachingAvailable: false,
    notes: 'Very low cost multimodal model via AWS Bedrock.',
    pricingUrl: 'https://aws.amazon.com/bedrock/pricing/',
    visionPricing: { strategy: 'openai-tiles', baseTokens: 85, tileTokens: 170 }
  },
];

export const getModelById = (id: string): ModelConfig | undefined =>
  models.find((m) => m.id === id);
