"use client";

import { useState } from "react";
import { useTokenSenseStore } from "@/lib/store";
import { getModelById } from "@/lib/models";
import { calculateCost } from "@/lib/costEngine";
import { Check, Copy, Download, ArrowRight, FileText } from "lucide-react";

interface ResultActionsProps {
  tokenCount: number;
  cost: number;
}

export function ResultActions({ tokenCount, cost }: ResultActionsProps) {
  const { selectedModelId, inputTokenCount, fileTokenCount, expectedOutputTokens } = useTokenSenseStore();
  const model = getModelById(selectedModelId);
  const [copied, setCopied] = useState(false);

  if (tokenCount === 0) return null;

  const totalInputTokens = inputTokenCount + fileTokenCount;
  const costs = model ? calculateCost(totalInputTokens, expectedOutputTokens, model) : null;

  const formatCost = (v: number) => {
    if (v === 0) return "$0.00";
    if (v < 0.0001) return `$${v.toFixed(6)}`;
    if (v < 0.01) return `$${v.toFixed(4)}`;
    return `$${v.toFixed(4)}`;
  };

  const handleCopy = () => {
      const markdown = [
        `### TokenSense AI Cost Estimate`,
        `| Metric | Value |`,
        `| :--- | :--- |`,
        `| **Model** | ${model?.name ?? "Unknown"} |`,
        `| **Input Tokens** | ${totalInputTokens.toLocaleString()} |`,
        `| **Input Cost** | ${formatCost(costs?.inputCost ?? 0)} |`,
        `| **Output Tokens** | ${expectedOutputTokens.toLocaleString()} |`,
        `| **Output Cost** | ${formatCost(costs?.outputCost ?? 0)} |`,
        `| **Total Cost** | **${formatCost(costs?.totalCost ?? cost)}** |`,
        ``,
        `*Generated by tokensense-ai.com*`,
      ].join("\n");

      navigator.clipboard.writeText(markdown).then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      });
    };

    const handleExportPDF = () => {
      // Add temporary print styles
      const style = document.createElement('style');
      style.innerHTML = `
        @media print {
          body * { visibility: hidden; }
          #print-report, #print-report * { visibility: visible; }
          #print-report { position: absolute; left: 0; top: 0; width: 100%; padding: 40px; }
        }
      `;
      document.head.appendChild(style);

      // Create a temporary element for printing
      const report = document.createElement('div');
      report.id = "print-report";
      report.innerHTML = `
        <div style="font-family: sans-serif;">
          <h1 style="color: #4f46e5;">TokenSense AI Cost Report</h1>
          <p style="color: #6b7280;">Date: ${new Date().toLocaleString()}</p>
          <hr/>
          <div style="margin: 20px 0;">
            <p><strong>Model:</strong> ${model?.name}</p>
            <p><strong>Input Tokens:</strong> ${totalInputTokens.toLocaleString()}</p>
            <p><strong>Output Tokens:</strong> ${expectedOutputTokens.toLocaleString()}</p>
            <h2 style="margin-top: 30px;">Cost Breakdown</h2>
            <p>Input Cost: ${formatCost(costs?.inputCost ?? 0)}</p>
            <p>Output Cost: ${formatCost(costs?.outputCost ?? 0)}</p>
            <p style="font-size: 24px; font-weight: bold; margin-top: 20px;">Total: ${formatCost(costs?.totalCost ?? cost)}</p>
          </div>
          <p style="margin-top: 50px; font-size: 12px; color: #9ca3af;">Generated at tokensense-ai.com</p>
        </div>
      `;
      document.body.appendChild(report);

      window.print();

      // Cleanup
      document.head.removeChild(style);
      document.body.removeChild(report);
    };

    const handleExport = () => {
    const csv =
      `Model,Input Tokens,Input Cost,Output Tokens,Output Cost,Total Cost\n` +
      `${model?.name},${totalInputTokens},${formatCost(costs?.inputCost ?? 0)},${expectedOutputTokens},${formatCost(costs?.outputCost ?? 0)},${formatCost(costs?.totalCost ?? cost)}`;
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    link.setAttribute("href", URL.createObjectURL(blob));
    link.setAttribute("download", `tokensense-ai-${Date.now()}.csv`);
    link.click();
  };

  const handleCompare = () => {
    const element = document.getElementById("comparison-section");
    element?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <div className="flex flex-wrap items-center gap-2 mt-4 pt-4 border-t border-slate-800/60">
      {/* Copy — primary action */}
      <button
        type="button"
        onClick={handleCopy}
        className={`
          inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-mono
          border transition-all duration-200
          ${copied
            ? "border-green-500/50 bg-green-500/10 text-green-400"
            : "border-plasma-500/30 bg-plasma-500/8 text-plasma-400 hover:bg-plasma-500/15 hover:border-plasma-400/60"
          }
        `}
      >
        {copied ? (
          <><Check className="w-3.5 h-3.5" /><span>Copied!</span></>
        ) : (
          <><Copy className="w-3.5 h-3.5" /><span>Copy Estimate</span></>
        )}
      </button>

      <button
        type="button"
        onClick={handleCompare}
        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-mono border border-slate-700/50 bg-slate-800/30 text-slate-400 hover:text-plasma-400 hover:border-plasma-500/30 transition-all duration-200"
      >
        <ArrowRight className="w-3.5 h-3.5" />
        <span>More Models</span>
      </button>

      <button
        type="button"
        onClick={handleExport}
        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-mono border border-slate-700/50 bg-slate-800/30 text-slate-400 hover:text-plasma-400 hover:border-plasma-500/30 transition-all duration-200"
      >
        <Download className="w-3.5 h-3.5" />
        <span>CSV</span>
      </button>

      <button
        type="button"
        onClick={handleExportPDF}
        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-mono border border-slate-700/50 bg-slate-800/30 text-slate-400 hover:text-plasma-400 hover:border-plasma-500/30 transition-all duration-200"
      >
        <FileText className="w-3.5 h-3.5" />
        <span>PDF</span>
      </button>
    </div>
  );
}

